// UI text in four languages: [Karakalpak, Uzbek, Russian, English]
// Add a key here, then use it in code as t('key'). Run `npm run check` to find missing keys.
export const STRINGS = {
  // ── Meta / navigation ──
  meta_tagline: ['Oqıw hám jumıs platforması', "O'qish va ish platformasi", 'Платформа обучения и карьеры', 'Learning & careers platform'],
  meta_description: ['Jumıs AI — Qaraqalpaqstan jasları ushın onlayn kurslar, testler, AI karyera keńesshisi hám vakansiyalar.', "Jumıs AI — Qoraqalpog'iston yoshlari uchun onlayn kurslar, testlar, AI karyera maslahatchisi va vakansiyalar.", 'Jumıs AI — онлайн-курсы, тесты, ИИ-карьерный консультант и вакансии для молодёжи Каракалпакстана.', 'Jumıs AI — online courses, tests, an AI career advisor and job vacancies for young people in Karakalpakstan.'],
  nav_home: ['Bas bet', 'Bosh sahifa', 'Главная', 'Dashboard'],
  nav_courses: ['Kurslar', 'Kurslar', 'Курсы', 'Courses'],
  nav_vacancies: ['Vakansiyalar', 'Vakansiyalar', 'Вакансии', 'Vacancies'],
  nav_ai: ['Ziyrek AI', 'Ziyrek AI', 'Ziyrek AI', 'Ziyrek AI'],
  nav_skill_test: ['Kónlikpe testi', "Ko'nikma testi", 'Тест навыков', 'Skill test'],
  nav_community: ['Járdem hám jámiyet', 'Yordam va hamjamiyat', 'Помощь и сообщество', 'Help & community'],
  nav_profile: ['Profil', 'Profil', 'Профиль', 'Profile'],
  nav_logout: ['Shıǵıw', 'Chiqish', 'Выйти', 'Log out'],
  nav_admin: ['Basqarıw paneli', 'Boshqaruv paneli', 'Панель управления', 'Admin panel'],
  nav_teaching: ['Oqıtıwshı paneli', "O'qituvchi paneli", 'Панель преподавателя', 'Teaching panel'],
  nav_org: ['Shólkem paneli', 'Tashkilot paneli', 'Панель организации', 'Organization panel'],
  toggle_theme: ['Tús rejimi', 'Rang rejimi', 'Тема оформления', 'Toggle theme'],
  notifications: ['Xabarlamalar', 'Bildirishnomalar', 'Уведомления', 'Notifications'],
  login: ['Kiriw', 'Kirish', 'Войти', 'Log in'],
  register: ['Dizimnen ótiw', "Ro'yxatdan o'tish", 'Регистрация', 'Sign up'],
  get_started: ['Baslaw', 'Boshlash', 'Начать', 'Get started'],
  privacy: ['Qupıyalılıq siyasatı', 'Maxfiylik siyosati', 'Политика конфиденциальности', 'Privacy policy'],
  footer_about: ['Úyreniń, ózińizdi sınap kóriń hám ármanıńızdaǵı jumısqa jetiń — Ziyrek AI járdeminde.', "O'rganing, o'zingizni sinab ko'ring va orzuingizdagi ishga erishing — Ziyrek AI yordamida.", 'Учитесь, проверяйте себя и находите работу мечты — вместе с Ziyrek AI.', 'Learn, test yourself and land the job you want — with help from Ziyrek AI.'],
  footer_platform: ['Platforma', 'Platforma', 'Платформа', 'Platform'],
  footer_community: ['Jámiyet', 'Hamjamiyat', 'Сообщество', 'Community'],
  footer_language: ['Til', 'Til', 'Язык', 'Language'],
  footer_made: ['Qaraqalpaqstanda jaratıldı', "Qoraqalpog'istonda yaratildi", 'Сделано в Каракалпакстане', 'Made in Karakalpakstan'],
  teachers: ['Oqıtıwshılar', "O'qituvchilar", 'Преподаватели', 'Teachers'],
  teachers_sub: ['Platformadaǵı kásiplik oqıtıwshılar menen tanısıń', "Platformadagi professional o'qituvchilar bilan tanishing", 'Познакомьтесь с преподавателями платформы', 'Meet the instructors on the platform'],
  go_home: ['Bas betke', 'Bosh sahifaga', 'На главную', 'Go home'],
  go_dashboard: ['Kabinetke ótiw', "Kabinetga o'tish", 'Перейти в кабинет', 'Go to dashboard'],
  err_403: ['Bul betke kiriwge ruxsat joq.', "Bu sahifaga kirishga ruxsat yo'q.", 'Нет доступа к этой странице.', "You don't have access to this page."],
  err_404: ['Bet tabılmadı.', 'Sahifa topilmadi.', 'Страница не найдена.', 'Page not found.'],
  err_500: ['Qátelik júz berdi. Keyinirek qaytalap kóriń.', "Xatolik yuz berdi. Keyinroq qayta urinib ko'ring.", 'Произошла ошибка. Попробуйте позже.', 'Something went wrong. Please try again later.'],

  // ── Landing ──
  hero_badge: ['AI menen jumıs jolı', "AI bilan ish yo'li", 'Карьерный путь с ИИ', 'Your AI-guided career path'],
  hero_title_1: ['Úyreniw —', "O'rganish —", 'Учёба —', 'Learning —'],
  hero_title_2: ['keleshekke', 'kelajak', 'шаг', 'a step'],
  hero_title_3: ['qaray qádem', 'sari qadam', 'в будущее', 'toward the future'],
  hero_lead: ['Onlayn kurslar, AI tallawı bar testler, sertifikatlar hám Qaraqalpaqstandaǵı vakansiyalar — bári bir jerde.', "Onlayn kurslar, AI tahlili bilan testlar, sertifikatlar va Qoraqalpog'istondagi vakansiyalar — barchasi bir joyda.", 'Онлайн-курсы, тесты с ИИ-анализом, сертификаты и вакансии Каракалпакстана — всё в одном месте.', 'Online courses, tests with AI analysis, certificates and vacancies across Karakalpakstan — all in one place.'],
  start_free: ['Biypul baslaw', 'Bepul boshlash', 'Начать бесплатно', 'Start for free'],
  browse_courses: ['Kurslardı kóriw', "Kurslarni ko'rish", 'Смотреть курсы', 'Browse courses'],
  hero_point_1: ['4 tilde', '4 tilda', 'На 4 языках', 'In 4 languages'],
  hero_point_2: ['AI keńesshi', 'AI maslahatchi', 'ИИ-консультант', 'AI advisor'],
  hero_point_3: ['Sertifikatlar', 'Sertifikatlar', 'Сертификаты', 'Certificates'],
  your_path: ['Sizdiń jolıńız', "Sizning yo'lingiz", 'Ваш путь', 'Your path'],
  path_1: ['Úyreniń', "O'rganing", 'Учитесь', 'Learn'],
  path_1_d: ['Video sabaqlar hám materiallar', 'Video darslar va materiallar', 'Видеоуроки и материалы', 'Video lessons and materials'],
  path_2: ['Sınap kóriń', "Sinab ko'ring", 'Проверьте себя', 'Test yourself'],
  path_2_d: ['Testler hám AI tallawı', 'Testlar va AI tahlili', 'Тесты и ИИ-анализ', 'Tests with AI analysis'],
  path_3: ['Sertifikat alıń', 'Sertifikat oling', 'Получите сертификат', 'Get certified'],
  path_3_d: ['Tekseriletuǵın sertifikat', 'Tekshiriladigan sertifikat', 'Проверяемый сертификат', 'A verifiable certificate'],
  path_4: ['Jumıs tabıń', 'Ish toping', 'Найдите работу', 'Find a job'],
  path_4_d: ['Sizge mas vakansiyalar', 'Sizga mos vakansiyalar', 'Подходящие вакансии', 'Vacancies that fit you'],
  float_report: ['AI karyera esabatı tayar', 'AI karyera hisoboti tayyor', 'ИИ-отчёт о карьере готов', 'AI career report ready'],
  float_jobs: ['{n} aktiv vakansiya', '{n} ta faol vakansiya', '{n} активных вакансий', '{n} open vacancies'],
  stat_courses: ['Kurslar', 'Kurslar', 'Курсов', 'Courses'],
  stat_lessons: ['Sabaqlar', 'Darslar', 'Уроков', 'Lessons'],
  stat_vacancies: ['Vakansiyalar', 'Vakansiyalar', 'Вакансий', 'Vacancies'],
  stat_users: ['Paydalanıwshılar', 'Foydalanuvchilar', 'Пользователей', 'Users'],
  features_eyebrow: ['Múmkinshilikler', 'Imkoniyatlar', 'Возможности', 'Features'],
  features_title: ['Oqıwdan jumısqa shekem bárshesi', 'Oʻqishdan ishgacha hammasi', 'Всё — от учёбы до работы', 'Everything from learning to hiring'],
  features_sub: ['Ziyrek AI hár qádemde sizge járdem beredi.', 'Ziyrek AI har qadamda sizga yordam beradi.', 'Ziyrek AI помогает на каждом шаге.', 'Ziyrek AI helps you at every step.'],
  feat_courses_t: ['Kurslar hám sabaqlar', 'Kurslar va darslar', 'Курсы и уроки', 'Courses & lessons'],
  feat_courses_d: ['YouTube yamasa júklengen video sabaqlar, materiallar, pikirler hám progress.', 'YouTube yoki yuklangan video darslar, materiallar, izohlar va progress.', 'Видеоуроки (YouTube или загруженные), материалы, комментарии и прогресс.', 'Video lessons (YouTube or uploaded), materials, comments and progress tracking.'],
  feat_tests_t: ['AI tallawlı testler', 'AI tahlilli testlar', 'Тесты с ИИ-анализом', 'Tests with AI analysis'],
  feat_tests_d: ['Sabaq, dárejelik hám juwmaqlawshı testler — AI qáteliklerińizdi túsindiredi.', 'Dars, daraja va yakuniy testlar — AI xatolaringizni tushuntiradi.', 'Уроковые, уровневые и итоговые тесты — ИИ объясняет ошибки.', 'Lesson, level and final tests — AI explains what to review.'],
  feat_assign_t: ['Tapsırmalar', 'Topshiriqlar', 'Задания', 'Assignments'],
  feat_assign_d: ['Juwabıńızdı jiberiń hám dárhal AI pikirin alıń, keyin oqıtıwshı bahalaydı.', 'Javobingizni yuboring va darhol AI fikrini oling, keyin oʻqituvchi baholaydi.', 'Сдайте работу и сразу получите отзыв ИИ, затем оценку преподавателя.', 'Submit work, get instant AI feedback, then a grade from your teacher.'],
  feat_ai_t: ['Ziyrek AI keńesshi', 'Ziyrek AI maslahatchi', 'Ziyrek AI-консультант', 'Ziyrek AI advisor'],
  feat_ai_d: ['CV-ńızdı oqıp, tayarlıǵıńızdı bahalaydı hám jeke jol kartasın dúzedi.', "CV'ingizni o'qib, tayyorgarligingizni baholaydi va shaxsiy yo'l xaritasini tuzadi.", 'Читает ваше резюме, оценивает готовность и строит личную дорожную карту.', 'Reads your CV, rates your readiness and builds a personal roadmap.'],
  feat_jobs_t: ['Vakansiyalar', 'Vakansiyalar', 'Вакансии', 'Vacancies'],
  feat_jobs_d: ['Shólkemler vakansiya járiyalaydı, siz bir basıwda arza beresiz.', 'Tashkilotlar vakansiya joylaydi, siz bir bosishda ariza berasiz.', 'Организации публикуют вакансии, вы откликаетесь в один клик.', 'Organizations post vacancies; you apply in one click.'],
  feat_purpose_t: ['Maqset keńisligi', 'Maqsad maydoni', 'Пространство целей', 'Purpose Space'],
  feat_purpose_d: ['AI sizge uqsas maqsetli adamlardı tabadı — baylanısıń hám birge ósiń.', "AI sizga o'xshash maqsadli odamlarni topadi — bog'laning va birga o'sing.", 'ИИ находит людей с похожими целями — знакомьтесь и растите вместе.', 'AI finds people with similar goals — connect and grow together.'],
  popular_courses: ['Ataqlı kurslar', 'Mashhur kurslar', 'Популярные курсы', 'Popular courses'],
  view_all: ['Barlıǵı', 'Barchasi', 'Все', 'View all'],
  how_eyebrow: ['Qalay isleydi', 'Qanday ishlaydi', 'Как это работает', 'How it works'],
  how_title: ['Tórt ápiwayı qádem', "To'rt oddiy qadam", 'Четыре простых шага', 'Four simple steps'],
  how_1: ['Dizimnen ótiń', "Ro'yxatdan o'ting", 'Зарегистрируйтесь', 'Create an account'],
  how_1_d: ['Oqıwshı, oqıtıwshı yamasa shólkem retinde.', "O'quvchi, o'qituvchi yoki tashkilot sifatida.", 'Как студент, преподаватель или организация.', 'As a student, teacher or organization.'],
  how_2: ['Kursqa jazılıń', 'Kursga yoziling', 'Запишитесь на курс', 'Enroll in a course'],
  how_2_d: ['Sabaqlardı kóriń, testler tapsırıń.', "Darslarni ko'ring, testlar topshiring.", 'Смотрите уроки, проходите тесты.', 'Watch lessons and take tests.'],
  how_3: ['AI tallawın alıń', 'AI tahlilini oling', 'Получите ИИ-анализ', 'Get your AI analysis'],
  how_3_d: ['Ziyrek AI kúshli hám ázzi táreplerińizdi kórsetedi.', "Ziyrek AI kuchli va zaif tomonlaringizni ko'rsatadi.", 'Ziyrek AI покажет сильные и слабые стороны.', 'Ziyrek AI shows your strengths and gaps.'],
  how_4: ['Jumısqa arza beriń', 'Ishga ariza bering', 'Откликнитесь на вакансию', 'Apply for jobs'],
  how_4_d: ['Sertifikat hám CV menen.', 'Sertifikat va CV bilan.', 'С сертификатом и резюме.', 'With your certificate and CV.'],
  latest_vacancies: ['Sońǵı vakansiyalar', 'Soʻnggi vakansiyalar', 'Свежие вакансии', 'Latest vacancies'],
  for_orgs_t: ['Shólkemler ushın', 'Tashkilotlar uchun', 'Для организаций', 'For organizations'],
  for_orgs_d: ['Vakansiya járiyalań, arzalardı basqarıń hám tayar kandidatlardı tabıń.', "Vakansiya joylang, arizalarni boshqaring va tayyor nomzodlarni toping.", 'Публикуйте вакансии, управляйте откликами и находите кандидатов.', 'Post vacancies, manage applications and find ready candidates.'],
  post_vacancy: ['Vakansiya járiyalaw', 'Vakansiya joylash', 'Разместить вакансию', 'Post a vacancy'],
  team_title: ['Bizdiń komanda', 'Bizning jamoa', 'Наша команда', 'Our team'],
  cta_title: ['Keleshegińizdi búgin baslań', 'Kelajagingizni bugun boshlang', 'Начните своё будущее сегодня', 'Start building your future today'],
  cta_sub: ['Biypul dizimnen ótiń hám birinshi kursıńızdı tańlań.', "Bepul ro'yxatdan o'ting va birinchi kursingizni tanlang.", 'Зарегистрируйтесь бесплатно и выберите первый курс.', 'Sign up for free and pick your first course.'],

  // ── Courses (public) ──
  courses_title: ['Kurslar', 'Kurslar', 'Курсы', 'Courses'],
  courses_sub: ['Kásiplik oqıtıwshılardan ámeliy kurslar', "Professional o'qituvchilardan amaliy kurslar", 'Практические курсы от профессиональных преподавателей', 'Practical courses from professional teachers'],
  search_courses: ['Kurs izlew...', 'Kurs qidirish...', 'Поиск курса...', 'Search courses...'],
  all: ['Barlıǵı', 'Barchasi', 'Все', 'All'],
  no_courses: ['Házirshe kurslar joq.', "Hozircha kurslar yo'q.", 'Пока нет курсов.', 'No courses yet.'],
  no_courses_found: ['Kurs tabılmadı. Basqa sóz benen izlep kóriń.', "Kurs topilmadi. Boshqa so'z bilan qidiring.", 'Курсы не найдены. Попробуйте другое слово.', 'No courses found. Try another keyword.'],
  unpublished: ['Járiyalanbaǵan', 'Nashr etilmagan', 'Не опубликован', 'Unpublished'],
  lessons_count: ['sabaq', 'dars', 'уроков', 'lessons'],
  students_count: ['oqıwshı', "o'quvchi", 'студентов', 'students'],
  back_to_courses: ['Barlıq kurslar', 'Barcha kurslar', 'Все курсы', 'All courses'],
  curriculum: ['Kurs baǵdarlaması', 'Kurs dasturi', 'Программа курса', 'Curriculum'],
  no_lessons: ['Házirshe sabaqlar joq.', "Hozircha darslar yo'q.", 'Пока нет уроков.', 'No lessons yet.'],
  start_learning: ['Oqıwdı baslaw', "O'qishni boshlash", 'Начать обучение', 'Start learning'],
  continue_learning: ['Oqıwdı dawam etiw', "O'qishni davom ettirish", 'Продолжить обучение', 'Continue learning'],
  login_to_learn: ['Biypul — tek dizimnen ótiw kerek', "Bepul — faqat ro'yxatdan o'tish kerak", 'Бесплатно — нужна только регистрация', 'Free — you only need an account'],
  video_lessons: ['video sabaq', 'video dars', 'видеоуроков', 'video lessons'],
  ai_feedback_included: ['AI pikiri hám tallawı', 'AI fikri va tahlili', 'Отзывы и анализ ИИ', 'AI feedback & analysis'],
  certificate_included: ['Juwmaqlawda sertifikat', 'Yakunda sertifikat', 'Сертификат по окончании', 'Certificate on completion'],
  teacher: ['Oqıtıwshı', "O'qituvchi", 'Преподаватель', 'Teacher'],
  about: ['Haqqında', 'Haqida', 'О себе', 'About'],
  education: ['Bilimi', "Ta'lim", 'Образование', 'Education'],
  website: ['Veb-sayt', 'Veb-sayt', 'Сайт', 'Website'],
  years_exp: ['{n} jıl tájiriybe', '{n} yil tajriba', 'Опыт {n} лет', '{n} years of experience'],

  // ── Vacancies (public) ──
  vacancies_title: ['Vakansiyalar', 'Vakansiyalar', 'Вакансии', 'Vacancies'],
  vacancies_sub: ['Kompaniyalar hám shólkemler járiyalaǵan jumıs orınları', "Kompaniyalar va tashkilotlar e'lon qilgan ish o'rinlari", 'Вакансии от компаний и организаций', 'Jobs posted by companies and organizations'],
  search_vacancies: ['Vakansiya yamasa kompaniya izlew...', 'Vakansiya yoki kompaniya qidirish...', 'Поиск вакансии или компании...', 'Search vacancies or companies...'],
  filter_job_type: ['Jumıs túri', 'Ish turi', 'Тип занятости', 'Job type'],
  filter_experience_level: ['Tájiriybe', 'Tajriba', 'Опыт', 'Experience'],
  filter_organization: ['Shólkem', 'Tashkilot', 'Организация', 'Organization'],
  filter_address: ['Mánzil', 'Manzil', 'Адрес', 'Location'],
  apply_filters: ['Qollanıw', "Qo'llash", 'Применить', 'Apply'],
  clear_filters: ['Tazalaw', 'Tozalash', 'Сбросить', 'Clear'],
  vacancies_found: ['vakansiya tabıldı', 'vakansiya topildi', 'вакансий найдено', 'vacancies found'],
  no_vacancies: ['Házirshe vakansiyalar joq.', "Hozircha vakansiyalar yo'q.", 'Пока нет вакансий.', 'No vacancies yet.'],
  no_vacancies_found: ['Vakansiya tabılmadı. Filtrlerdi ózgertip kóriń.', "Vakansiya topilmadi. Filtrlarni o'zgartirib ko'ring.", 'Вакансии не найдены. Измените фильтры.', 'No vacancies found. Try other filters.'],
  job_full_time: ['Tolıq kún', "To'liq kun", 'Полный день', 'Full-time'],
  job_part_time: ['Yarım kún', 'Yarim kun', 'Неполный день', 'Part-time'],
  job_contract: ['Shártnama', 'Shartnoma', 'Контракт', 'Contract'],
  job_internship: ['Stajirovka', 'Stajirovka', 'Стажировка', 'Internship'],
  job_remote: ['Qashıqtan', 'Masofaviy', 'Удалённо', 'Remote'],
  exp_no_experience: ['Tájiriybesiz', 'Tajribasiz', 'Без опыта', 'No experience'],
  exp_junior: ['Junior', 'Junior', 'Junior', 'Junior'],
  exp_mid: ['Middle', 'Middle', 'Middle', 'Middle'],
  exp_senior: ['Senior', 'Senior', 'Senior', 'Senior'],
  exp_lead: ['Lead', 'Lead', 'Lead', 'Lead'],
  back_to_vacancies: ['Barlıq vakansiyalar', 'Barcha vakansiyalar', 'Все вакансии', 'All vacancies'],
  deadline: ['Arza múddeti', 'Ariza muddati', 'Срок подачи', 'Deadline'],
  posted: ['Járiyalandı', "E'lon qilindi", 'Опубликовано', 'Posted'],
  cancelled: ['Biykar etildi', 'Bekor qilindi', 'Отменена', 'Cancelled'],
  active: ['Aktiv', 'Faol', 'Активна', 'Active'],
  vacancy_cancelled_title: ['Bul vakansiya biykar etildi', 'Bu vakansiya bekor qilindi', 'Эта вакансия отменена', 'This vacancy was cancelled'],
  reason: ['Sebebi', 'Sababi', 'Причина', 'Reason'],
  ai_analysis: ['AI tallawı', 'AI tahlili', 'Анализ ИИ', 'AI analysis'],
  job_description: ['Jumıs haqqında', 'Ish haqida', 'Описание работы', 'Job description'],
  apply_title: ['Arza beriw', 'Ariza berish', 'Откликнуться', 'Apply'],
  vacancy_expired: ['Arza múddeti tamamlandı.', 'Ariza muddati tugagan.', 'Срок подачи истёк.', 'The application deadline has passed.'],
  vacancy_closed: ['Bul vakansiya jabıq.', 'Bu vakansiya yopilgan.', 'Эта вакансия закрыта.', 'This vacancy is closed.'],
  login_to_apply: ['Arza beriw ushın kiriń', 'Ariza berish uchun kiring', 'Войдите, чтобы откликнуться', 'Log in to apply'],
  applied: ['Siz arza berdińiz', 'Siz ariza berdingiz', 'Вы откликнулись', 'You have applied'],
  app_status: ['Jaǵdayı', 'Holati', 'Статус', 'Status'],
  app_submitted: ['Jiberildi', 'Yuborildi', 'Отправлен', 'Submitted'],
  app_reviewed: ['Kórip shıǵıldı', "Ko'rib chiqildi", 'Просмотрен', 'Reviewed'],
  app_accepted: ['Qabıl etildi', 'Qabul qilindi', 'Принят', 'Accepted'],
  app_rejected: ['Biykarlandı', 'Rad etildi', 'Отклонён', 'Rejected'],
  app_cancelled: ['Vakansiya biykar etildi', 'Vakansiya bekor qilindi', 'Вакансия отменена', 'Vacancy cancelled'],
  orgs_cannot_apply: ['Shólkem akkauntları arza bere almaydı.', 'Tashkilot akkauntlari ariza bera olmaydi.', 'Аккаунты организаций не могут откликаться.', 'Organization accounts cannot apply.'],
  cover_letter: ['Qosımsha xat', 'Qo‘shimcha xat', 'Сопроводительное письмо', 'Cover letter'],
  cover_letter_ph: ['Ne ushın bul jumısqa mas ekenińizdi qısqasha jazıń...', 'Nega bu ishga mos ekanligingizni qisqacha yozing...', 'Кратко напишите, почему вы подходите...', 'Briefly say why you are a good fit...'],
  cv_attached_auto: ['Profilińizdegi CV avtomat túrde qosıladı', 'Profilingizdagi CV avtomatik qo‘shiladi', 'Резюме из профиля будет приложено автоматически', 'The CV from your profile will be attached'],
  attach_cv: ['CV qosıw (PDF, DOC)', "CV qo'shish (PDF, DOC)", 'Приложить резюме (PDF, DOC)', 'Attach CV (PDF, DOC)'],
  sending: ['Jiberilmekte...', 'Yuborilmoqda...', 'Отправка...', 'Sending...'],
  apply_now: ['Arza beriw', 'Ariza berish', 'Откликнуться', 'Apply now'],
  similar_vacancies: ['Uqsas vakansiyalar', "O'xshash vakansiyalar", 'Похожие вакансии', 'Similar vacancies'],
  salary: ['Aylıq', 'Maosh', 'Зарплата', 'Salary'],

  // ── Community ──
  community_title: ['Járdem hám jámiyet', 'Yordam va hamjamiyat', 'Помощь и сообщество', 'Help & community'],
  community_sub: ['Video túsindirmeler, paydalı siltemeler, ilajlar hám qollap-quwatlaw', "Video tushuntirishlar, foydali havolalar, tadbirlar va qo'llab-quvvatlash", 'Видео-объяснения, полезные ссылки, события и поддержка', 'Video guides, useful links, events and support'],
  find_people: ['Adamlardı tabıw', 'Odamlarni topish', 'Найти людей', 'Find people'],
  tab_videos: ['Video túsindirmeler', 'Video tushuntirishlar', 'Видео-объяснения', 'Video guides'],
  tab_links: ['Paydalı siltemeler', 'Foydali havolalar', 'Полезные ссылки', 'Useful links'],
  tab_investors: ['Investorlar', 'Investorlar', 'Инвесторы', 'Investors'],
  tab_events: ['Ilajlar', 'Tadbirlar', 'События', 'Events'],
  tab_news: ['Jańalıqlar', 'Yangiliklar', 'Новости', 'News'],
  tab_support: ['Qollap-quwatlaw', "Qo'llab-quvvatlash", 'Поддержка', 'Support'],
  tab_founders: ['Tiykarlawshılar', 'Asoschilar', 'Основатели', 'Founders'],
  nothing_yet: ['Házirshe hesh nárse joq.', "Hozircha hech narsa yo'q.", 'Пока ничего нет.', 'Nothing here yet.'],
  open_video: ['Videonı ashıw', 'Videoni ochish', 'Открыть видео', 'Open video'],
  open: ['Ashıw', 'Ochish', 'Открыть', 'Open'],
  details: ['Tolıǵıraq', 'Batafsil', 'Подробнее', 'Details'],
  support_title: ['Qollap-quwatlaw orayı', "Qo'llab-quvvatlash markazi", 'Центр поддержки', 'Support center'],
  support_sub: ['Sorawıńız bar ma? Biz járdem beriwge tayarmız!', 'Savolingiz bormi? Biz yordam berishga tayyormiz!', 'Есть вопрос? Мы готовы помочь!', 'Have a question? We are happy to help!'],
  coming_soon: ['Tez arada.', 'Tez orada.', 'Скоро.', 'Coming soon.'],

  // ── Auth ──
  login_title: ['Qaytıp kelgenińiz menen!', 'Xush kelibsiz!', 'С возвращением!', 'Welcome back!'],
  register_title: ['Akkaunt jaratıw', 'Akkaunt yaratish', 'Создать аккаунт', 'Create your account'],
  email: ['Email', 'Email', 'Email', 'Email'],
  password: ['Parol', 'Parol', 'Пароль', 'Password'],
  forgot_password: ['Paroldi umıttıńız ba?', 'Parolni unutdingizmi?', 'Забыли пароль?', 'Forgot password?'],
  no_account: ['Akkauntıńız joq pa?', "Akkauntingiz yo'qmi?", 'Нет аккаунта?', "Don't have an account?"],
  have_account: ['Akkauntıńız bar ma?', 'Akkauntingiz bormi?', 'Уже есть аккаунт?', 'Already have an account?'],
  full_name: ['Tolıq atı', "To'liq ism", 'Полное имя', 'Full name'],
  password_hint: ['Keminde 8 belgi', 'Kamida 8 ta belgi', 'Минимум 8 символов', 'At least 8 characters'],
  who_are_you: ['Siz kimsiz?', 'Siz kimsiz?', 'Кто вы?', 'Who are you?'],
  type_student: ['Oqıwshı / paydalanıwshı', "O'quvchi / foydalanuvchi", 'Студент / пользователь', 'Student / learner'],
  type_student_d: ['Úyreniwshiler hám jumıs izlewshiler ushın', "O'rganuvchilar va ish izlovchilar uchun", 'Для учащихся и соискателей', 'For learners and job seekers'],
  type_teacher: ['Oqıtıwshı', "O'qituvchi", 'Преподаватель', 'Teacher'],
  type_teacher_d: ['Kurs jaratıw ushın (admin tastıyıqlaydı)', 'Kurs yaratish uchun (admin tasdiqlaydi)', 'Для создания курсов (подтверждает админ)', 'To create courses (approved by an admin)'],
  type_organization: ['Shólkem / kompaniya', 'Tashkilot / kompaniya', 'Организация / компания', 'Organization / company'],
  type_organization_d: ['Vakansiya járiyalaw hám kandidat tabıw ushın', 'Vakansiya joylash va nomzod topish uchun', 'Для размещения вакансий и поиска кандидатов', 'To post vacancies and find candidates'],
  organization_name: ['Shólkem atı', 'Tashkilot nomi', 'Название организации', 'Organization name'],
  create_account: ['Akkaunt jaratıw', 'Akkaunt yaratish', 'Создать аккаунт', 'Create account'],
  agree_privacy: ['Dizimnen ótip, siz kelisesiz:', "Ro'yxatdan o'tib, siz rozilik bildirasiz:", 'Регистрируясь, вы соглашаетесь с', 'By signing up you agree to the'],
  bad_login: ['Email/telefon yamasa parol qáte.', "Email/telefon yoki parol noto'g'ri.", 'Неверный email/телефон или пароль.', 'Wrong email/phone or password.'],
  email_or_phone: ['Email yamasa telefon nomeri', 'Email yoki telefon raqami', 'Email или номер телефона', 'Email or phone number'],
  email_or_phone_ph: ['siz@mısal.uz yamasa +998 90 123 45 67', 'siz@misol.uz yoki +998 90 123 45 67', 'vy@primer.uz или +998 90 123 45 67', 'you@example.com or +998 90 123 45 67'],
  phone_login_hint: ['Bul nomer menen de kiriwińiz múmkin.', 'Bu raqam bilan ham kirishingiz mumkin.', 'По этому номеру тоже можно будет войти.', 'You can also log in with this number.'],
  err_phone: ['Durıs telefon nomerin jazıń, mısalı +998 90 123 45 67.', "To'g'ri telefon raqamini kiriting, masalan +998 90 123 45 67.", 'Введите корректный номер, например +998 90 123 45 67.', 'Please enter a valid phone number, e.g. +998 90 123 45 67.'],
  err_phone_required: ['Telefon nomerin jazıń.', 'Telefon raqamini kiriting.', 'Укажите номер телефона.', 'Please enter your phone number.'],
  err_phone_taken: ['Bul telefon nomeri menen akkaunt bar.', "Bu telefon raqami bilan akkaunt mavjud.", 'Аккаунт с этим номером уже существует.', 'An account with this phone number already exists.'],
  err_name: ['Atıńızdı jazıń.', 'Ismingizni yozing.', 'Укажите имя.', 'Please enter your name.'],
  err_email: ['Durıs email jazıń.', "To'g'ri email kiriting.", 'Введите корректный email.', 'Please enter a valid email.'],
  err_type: ['Akkaunt túrin tańlań.', 'Akkaunt turini tanlang.', 'Выберите тип аккаунта.', 'Please choose an account type.'],
  err_org_name: ['Shólkem atın jazıń.', 'Tashkilot nomini yozing.', 'Укажите название организации.', 'Please enter the organization name.'],
  err_email_taken: ['Bul email menen akkaunt bar. Kiriwdi sınap kóriń.', "Bu email bilan akkaunt mavjud. Kirib ko'ring.", 'Аккаунт с этим email уже существует. Попробуйте войти.', 'An account with this email already exists. Try logging in.'],
  welcome_msg: ['Xosh keldińiz, {name}!', 'Xush kelibsiz, {name}!', 'Добро пожаловать, {name}!', 'Welcome, {name}!'],
  onboarding_title: ['Xosh keldińiz! Siz kimsiz?', 'Xush kelibsiz! Siz kimsiz?', 'Добро пожаловать! Кто вы?', 'Welcome! Who are you?'],
  onboarding_sub: ['Akkaunt túrin tańlań — bul tájiriybeńizdi jekelestiriwge járdem beredi.', "Akkaunt turini tanlang — bu tajribangizni moslashtirishga yordam beradi.", 'Выберите тип аккаунта — так мы настроим платформу под вас.', 'Choose your account type so we can tailor your experience.'],
  continue: ['Dawam etiw', 'Davom etish', 'Продолжить', 'Continue'],
  reset_title: ['Paroldi tiklew', 'Parolni tiklash', 'Восстановление пароля', 'Reset password'],
  reset_sent: ['Eger bul akkaunt dizimde bolsa, siltemeni akkaunt emailine jiberdik.', "Agar bu akkaunt ro'yxatda bo'lsa, havolani akkaunt emailiga yubordik.", 'Если аккаунт зарегистрирован, мы отправили ссылку на его email.', "If this account is registered, we have sent a reset link to its email."],
  send_reset: ['Siltemeni jiberiw', 'Havolani yuborish', 'Отправить ссылку', 'Send reset link'],
  back_to_login: ['Kiriwge qaytıw', 'Kirishga qaytish', 'Вернуться ко входу', 'Back to login'],
  reset_email_body: ['Jańa parol ornatıw ushın tómendegi siltemeni ashıń (1 saat jaramlı):', "Yangi parol o'rnatish uchun quyidagi havolani oching (1 soat amal qiladi):", 'Чтобы задать новый пароль, откройте ссылку (действует 1 час):', 'Open this link to set a new password (valid for 1 hour):'],
  reset_invalid: ['Silteme jaramsız yamasa múddeti ótken.', "Havola yaroqsiz yoki muddati o'tgan.", 'Ссылка недействительна или устарела.', 'This link is invalid or has expired.'],
  new_password: ['Jańa parol', 'Yangi parol', 'Новый пароль', 'New password'],
  password_changed: ['Parol ózgertildi.', "Parol o'zgartirildi.", 'Пароль изменён.', 'Password changed.'],
  save: ['Saqlaw', 'Saqlash', 'Сохранить', 'Save'],

  // ── Dashboards ──
  welcome_back: ['Sálem, {name} 👋', 'Salom, {name} 👋', 'Привет, {name} 👋', 'Welcome back, {name} 👋'],
  student_welcome_sub: ['Búgin siz ushın usınıslar mına.', 'Bugun siz uchun tavsiyalar.', 'Вот что мы рекомендуем вам сегодня.', "Here's what we recommend for you today."],
  my_courses: ['Meniń kurslarım', 'Mening kurslarim', 'Мои курсы', 'My courses'],
  avg_score: ['Ortasha ball', "O'rtacha ball", 'Средний балл', 'Average score'],
  certificates: ['Sertifikatlar', 'Sertifikatlar', 'Сертификаты', 'Certificates'],
  upcoming_sessions: ['Kelesi sabaqlar', 'Kelgusi darslar', 'Ближайшие занятия', 'Upcoming sessions'],
  ai_cta_title: ['Ziyrek AI karyera tallawı', 'Ziyrek AI karyera tahlili', 'Карьерный анализ Ziyrek AI', 'Ziyrek AI career analysis'],
  ai_cta_sub: ['CV hám profilińizdi tallap, jeke jol kartasın alıń.', "CV va profilingizni tahlil qilib, shaxsiy yo'l xaritasini oling.", 'Анализ резюме и профиля с личной дорожной картой.', 'Get your CV and profile analysed with a personal roadmap.'],
  ai_cta_last: ['Sońǵı tallaw: {date}', "So'nggi tahlil: {date}", 'Последний анализ: {date}', 'Last analysis: {date}'],
  open_report: ['Esabattı ashıw', 'Hisobotni ochish', 'Открыть отчёт', 'Open report'],
  all_courses: ['Barlıq kurslar', 'Barcha kurslar', 'Все курсы', 'All courses'],
  your_progress: ['Progress', 'Progress', 'Прогресс', 'Your progress'],
  no_enrolled: ['Siz ele kursqa jazılmadıńız.', 'Siz hali kursga yozilmagansiz.', 'Вы ещё не записались на курс.', "You haven't enrolled in a course yet."],
  recommended_courses: ['Usınılǵan kurslar', 'Tavsiya etilgan kurslar', 'Рекомендуемые курсы', 'Recommended courses'],
  recommended_vacancies: ['Usınılǵan vakansiyalar', 'Tavsiya etilgan vakansiyalar', 'Рекомендуемые вакансии', 'Recommended vacancies'],
  upcoming_schedule: ['Kelesi kesteler', 'Kelgusi jadval', 'Ближайшее расписание', 'Upcoming schedule'],
  manage: ['Basqarıw', 'Boshqarish', 'Управлять', 'Manage'],
  no_schedule: ['Kesteler joq.', "Jadval yo'q.", 'Расписания нет.', 'No upcoming sessions.'],
  add: ['Qosıw', "Qo'shish", 'Добавить', 'Add'],
  recent_results: ['Sońǵı nátiyjeler', "So'nggi natijalar", 'Последние результаты', 'Recent results'],
  no_results: ['Ele nátiyjeler joq.', "Hali natijalar yo'q.", 'Пока нет результатов.', 'No results yet.'],
  teacher_welcome_sub: ['Kurslarıńız hám oqıwshılarıńız haqqında qısqasha.', "Kurslaringiz va o'quvchilaringiz haqida qisqacha.", 'Кратко о ваших курсах и студентах.', 'A quick look at your courses and students.'],
  teacher_pending_title: ['Oqıtıwshı akkauntı tastıyıqlawdı kútpekte', "O'qituvchi akkaunti tasdiqlashni kutmoqda", 'Аккаунт преподавателя ожидает подтверждения', 'Your teacher account is awaiting approval'],
  teacher_pending_text: ['Admin tastıyıqlaǵannan keyin kurs jarata alasız. Házir oqıtıwshı profilińizdi toltırıń.', "Admin tasdiqlagandan so'ng kurs yarata olasiz. Hozir o'qituvchi profilingizni to'ldiring.", 'После подтверждения админом вы сможете создавать курсы. Пока заполните профиль преподавателя.', 'Once an admin approves you, you can create courses. Meanwhile, fill in your teacher profile.'],
  students: ['Oqıwshılar', "O'quvchilar", 'Студенты', 'Students'],
  to_review: ['Tekseriw kerek', 'Tekshirish kerak', 'На проверку', 'To review'],
  new_course: ['Jańa kurs', 'Yangi kurs', 'Новый курс', 'New course'],
  public_teacher_profile: ['Ashıq oqıtıwshı profili', "Ochiq o'qituvchi profili", 'Публичный профиль', 'Public teacher profile'],
  no_courses_teacher: ['Ele kurslar joq. Birinshi kursıńızdı jaratıń!', "Hali kurslar yo'q. Birinchi kursingizni yarating!", 'Курсов пока нет. Создайте первый!', 'No courses yet. Create your first one!'],
  nothing_to_review: ['Tekseriletuǵın jumıslar joq. Ájayıp!', "Tekshiriladigan ishlar yo'q. Ajoyib!", 'Нечего проверять. Отлично!', 'Nothing to review. Great!'],
  org_welcome_sub: ['Vakansiyalarıńızdı basqarıń hám kandidatlardı tabıń.', 'Vakansiyalaringizni boshqaring va nomzodlarni toping.', 'Управляйте вакансиями и находите кандидатов.', 'Manage your vacancies and find candidates.'],
  active_vacancies: ['Aktiv vakansiyalar', 'Faol vakansiyalar', 'Активные вакансии', 'Active vacancies'],
  applications: ['Arzalar', 'Arizalar', 'Отклики', 'Applications'],
  new_applications: ['Jańa arzalar', 'Yangi arizalar', 'Новые отклики', 'New applications'],
  open_candidates: ['Ashıq kandidatlar', 'Ochiq nomzodlar', 'Открытые кандидаты', 'Open candidates'],
  browse_candidates: ['Kandidatlardı kóriw', "Nomzodlarni ko'rish", 'Смотреть кандидатов', 'Browse candidates'],
  my_vacancies: ['Meniń vakansiyalarım', 'Mening vakansiyalarim', 'Мои вакансии', 'My vacancies'],
  no_vacancies_org: ['Ele vakansiyalar joq.', "Hali vakansiyalar yo'q.", 'Вакансий пока нет.', 'No vacancies yet.'],
  recent_applications: ['Sońǵı arzalar', "So'nggi arizalar", 'Последние отклики', 'Recent applications'],
  no_applications: ['Ele arzalar joq.', "Hali arizalar yo'q.", 'Откликов пока нет.', 'No applications yet.'],
  admin_welcome_sub: ['Platforma boyınsha ulıwma kórinis.', "Platforma bo'yicha umumiy ko'rinish.", 'Общая картина по платформе.', 'Platform overview.'],
  pending_teachers: ['{n} oqıtıwshı tastıyıqlawdı kútpekte', "{n} ta o'qituvchi tasdiqlashni kutmoqda", '{n} преподавателей ждут подтверждения', '{n} teachers waiting for approval'],
  enrollments: ['Jazılıwlar', 'Yozilishlar', 'Записи на курсы', 'Enrollments'],
  tests_taken: ['Tapsırılǵan testler', 'Topshirilgan testlar', 'Пройдено тестов', 'Tests taken'],
  new_users: ['Jańa paydalanıwshılar', 'Yangi foydalanuvchilar', 'Новые пользователи', 'New users'],

  // ── Learning ──
  gate_title: ['Aldın aldıńǵı sabaqtıń testin tapsırıń', 'Avval oldingi dars testini topshiring', 'Сначала пройдите тест прошлого урока', 'First, take the previous lesson test'],
  gate_text: ['«{lesson}» sabaǵı boyınsha qısqa test bul sabaqtı ashadı.', '«{lesson}» darsi bo‘yicha qisqa test bu darsni ochadi.', 'Короткий тест по уроку «{lesson}» откроет этот урок.', 'A short test on "{lesson}" unlocks this lesson.'],
  start_test: ['Testti baslaw', 'Testni boshlash', 'Начать тест', 'Start test'],
  write_comment: ['Pikir jazıń...', 'Izoh yozing...', 'Напишите комментарий...', 'Write a comment...'],
  send: ['Jiberiw', 'Yuborish', 'Отправить', 'Send'],
  confirm_delete: ['Rasında óshiriwdi qáleysiz be?', "Haqiqatan ham o'chirmoqchimisiz?", 'Точно удалить?', 'Are you sure you want to delete this?'],
  delete: ['Óshiriw', "O'chirish", 'Удалить', 'Delete'],
  no_comments: ['Ele pikirler joq. Birinshi bolıń!', "Hali izohlar yo'q. Birinchi bo'ling!", 'Комментариев пока нет. Будьте первым!', 'No comments yet. Be the first!'],
  download: ['Júklep alıw', 'Yuklab olish', 'Скачать', 'Download'],
  no_materials: ['Bul sabaqta materiallar joq.', "Bu darsda materiallar yo'q.", 'В этом уроке нет материалов.', 'No materials for this lesson.'],
  add_material: ['Material qosıw', "Material qo'shish", 'Добавить материал', 'Add material'],
  title: ['Atı', 'Nomi', 'Название', 'Title'],
  choose_file: ['Fayl tańlaw', 'Fayl tanlash', 'Выбрать файл', 'Choose file'],
  uploading: ['Júklenbekte...', 'Yuklanmoqda...', 'Загрузка...', 'Uploading...'],
  upload: ['Júklew', 'Yuklash', 'Загрузить', 'Upload'],
  due: ['Múddeti', 'Muddati', 'Срок', 'Due'],
  your_answer: ['Sizdiń juwabıńız', 'Sizning javobingiz', 'Ваш ответ', 'Your answer'],
  attached_file: ['Qosılǵan fayl', "Qo'shilgan fayl", 'Прикреплённый файл', 'Attached file'],
  ai_feedback: ['AI pikiri', 'AI fikri', 'Отзыв ИИ', 'AI feedback'],
  grade: ['Baha', 'Baho', 'Оценка', 'Grade'],
  write_answer: ['Juwabıńızdı usı jerge jazıń...', 'Javobingizni shu yerga yozing...', 'Напишите ответ здесь...', 'Write your answer here...'],
  attach_file: ['Fayl qosıw', "Fayl qo'shish", 'Прикрепить файл', 'Attach file'],
  ai_checking: ['AI tekserip atır...', 'AI tekshirmoqda...', 'ИИ проверяет...', 'AI is checking...'],
  resubmit: ['Qayta jiberiw', 'Qayta yuborish', 'Отправить снова', 'Resubmit'],
  submit: ['Jiberiw', 'Yuborish', 'Отправить', 'Submit'],
  no_assignments: ['Bul sabaqta tapsırmalar joq.', "Bu darsda topshiriqlar yo'q.", 'В этом уроке нет заданий.', 'No assignments for this lesson.'],
  no_video: ['Video qosılmaǵan', "Video qo'shilmagan", 'Видео не добавлено', 'No video added'],
  lesson: ['Sabaq', 'Dars', 'Урок', 'Lesson'],
  lessons: ['Sabaqlar', 'Darslar', 'Уроки', 'Lessons'],
  completed: ['Tamamlandı', 'Tugallandi', 'Пройден', 'Completed'],
  mark_complete: ['Tamamlandı dep belgilew', 'Tugallandi deb belgilash', 'Отметить пройденным', 'Mark as complete'],
  lesson_test_hint: ['Bul sabaq boyınsha bilimińizdi tekseriń', "Bu dars bo'yicha bilimingizni tekshiring", 'Проверьте знания по этому уроку', 'Check what you learned in this lesson'],
  retake: ['Qayta tapsırıw', 'Qayta topshirish', 'Пройти снова', 'Retake'],
  comments: ['Pikirler', 'Izohlar', 'Комментарии', 'Comments'],
  materials: ['Materiallar', 'Materiallar', 'Материалы', 'Materials'],
  assignments: ['Tapsırmalar', 'Topshiriqlar', 'Задания', 'Assignments'],
  course_tests: ['Kurs testleri', 'Kurs testlari', 'Тесты курса', 'Course tests'],
  questions_h: ['Sorawlar', 'Savollar', 'Вопросы', 'Questions'],
  questions: ['soraw', 'savol', 'вопросов', 'questions'],
  minutes: ['minut', 'daqiqa', 'мин', 'min'],
  pass_mark: ['Ótiw balı', "O'tish bali", 'Проходной балл', 'Pass mark'],
  certificate: ['Sertifikat', 'Sertifikat', 'Сертификат', 'Certificate'],
  cert_ready: ['Sertifikatıńız tayar! 🎉', 'Sertifikatingiz tayyor! 🎉', 'Ваш сертификат готов! 🎉', 'Your certificate is ready! 🎉'],
  cert_how: ['Barlıq sabaqlardı tamamlań hám juwmaqlawshı testten ótiń — sertifikat avtomat beriledi.', "Barcha darslarni tugating va yakuniy testdan o'ting — sertifikat avtomatik beriladi.", 'Пройдите все уроки и итоговый тест — сертификат выдаётся автоматически.', 'Complete every lesson and pass the final test — the certificate is issued automatically.'],
  view_certificate: ['Sertifikattı kóriw', "Sertifikatni ko'rish", 'Открыть сертификат', 'View certificate'],
  enroll_title: ['Kursqa jazılıw', 'Kursga yozilish', 'Запись на курс', 'Enroll in this course'],
  enroll_sub: ['Birinshi sabaq biypul. Qalǵanların kóriw ushın jazılıń.', 'Birinchi dars bepul. Qolganlarini ko‘rish uchun yoziling.', 'Первый урок бесплатный. Чтобы открыть остальные, запишитесь.', 'The first lesson is free. Enroll to unlock the rest.'],
  code_sent_to: ['Tastıyıqlaw kodı {email} mánziline jiberildi.', 'Tasdiqlash kodi {email} manziliga yuborildi.', 'Код подтверждения отправлен на {email}.', 'A verification code was sent to {email}.'],
  verification_code: ['Tastıyıqlaw kodı', 'Tasdiqlash kodi', 'Код подтверждения', 'Verification code'],
  verify: ['Tastıyıqlaw', 'Tasdiqlash', 'Подтвердить', 'Verify'],
  resend_code: ['Kodtı qayta jiberiw', 'Kodni qayta yuborish', 'Отправить код снова', 'Resend code'],
  id_number: ['ID nomeri (pasport)', 'ID raqami (pasport)', 'Номер ID (паспорт)', 'ID number (passport)'],
  phone: ['Telefon', 'Telefon', 'Телефон', 'Phone'],
  enroll_btn: ['Jazılıw', 'Yozilish', 'Записаться', 'Enroll'],
  fill_required: ['Mindetli maydanlardı toltırıń.', "Majburiy maydonlarni to'ldiring.", 'Заполните обязательные поля.', 'Please fill in the required fields.'],
  enrollment_success: ['Siz kursqa tabıslı jazıldıńız! Úlken ómir jolına birinshi qádem.', "Siz kursga muvaffaqiyatli yozildingiz! Katta hayot sari birinchi qadam.", 'Вы успешно записались на курс! Первый шаг к большой цели.', 'You are enrolled! Your first step toward big goals.'],
  enroll_email: ['Siz «{course}» kursına jazılıp atırsız. Tastıyıqlaw kodıńız:', '«{course}» kursiga yozilmoqdasiz. Tasdiqlash kodingiz:', 'Вы записываетесь на курс «{course}». Ваш код подтверждения:', 'You are enrolling in "{course}". Your verification code:'],
  code_valid_15: ['Kod 15 minut jaramlı.', 'Kod 15 daqiqa amal qiladi.', 'Код действует 15 минут.', 'The code is valid for 15 minutes.'],
  code_expired: ['Kodtıń múddeti ótti. Jańa kod alıń.', "Kod muddati o'tdi. Yangi kod oling.", 'Код устарел. Запросите новый.', 'The code expired. Please request a new one.'],
  invalid_code: ['Kod qáte.', "Kod noto'g'ri.", 'Неверный код.', 'Invalid code.'],
  cert_issued: ['Sertifikat berildi! 🎓', 'Sertifikat berildi! 🎓', 'Сертификат выдан! 🎓', 'Certificate issued! 🎓'],
  lesson_completed: ['Sabaq tamamlandı ✔', 'Dars tugallandi ✔', 'Урок пройден ✔', 'Lesson completed ✔'],
  saved: ['Saqlandı', 'Saqlandi', 'Сохранено', 'Saved'],
  already_reviewed: ['Bul jumıs áldeqashan bahalandı.', 'Bu ish allaqachon baholangan.', 'Эта работа уже оценена.', 'This work has already been graded.'],
  answer_required: ['Juwap jazıń yamasa fayl qosıń.', "Javob yozing yoki fayl qo'shing.", 'Напишите ответ или прикрепите файл.', 'Write an answer or attach a file.'],
  submitted_ai: ['Jiberildi! AI pikiri qosıldı.', "Yuborildi! AI fikri qo'shildi.", 'Отправлено! Отзыв ИИ добавлен.', 'Submitted! AI feedback added.'],
  submitted: ['Jiberildi!', 'Yuborildi!', 'Отправлено!', 'Submitted!'],
  next_question: ['Keyingi soraw', 'Keyingi savol', 'Следующий вопрос', 'Next question'],
  finish_test: ['Testti tamamlaw', 'Testni yakunlash', 'Завершить тест', 'Finish test'],
  ai_analyzing: ['AI tallap atır...', 'AI tahlil qilmoqda...', 'ИИ анализирует...', 'AI is analysing...'],
  noscript_quiz: ['JavaScript óshirilgen: barlıq sorawlar bir bette kórsetilgen.', "JavaScript o'chirilgan: barcha savollar bitta sahifada.", 'JavaScript выключен: все вопросы на одной странице.', 'JavaScript is off: all questions are shown on one page.'],
  no_questions: ['Bul testte ele sorawlar joq.', "Bu testda hali savollar yo'q.", 'В этом тесте пока нет вопросов.', 'This test has no questions yet.'],
  per_question: ['hár sorawǵa', 'har savolga', 'на вопрос', 'per question'],
  test_rules: ['Hár sorawǵa waqıt sheklengen. Waqıt pitkende keyingi sorawǵa ótiledi. Nátiyjeni AI tallaydı.', "Har savolga vaqt cheklangan. Vaqt tugasa keyingi savolga o'tiladi. Natijani AI tahlil qiladi.", 'На каждый вопрос отведено время. По истечении — переход к следующему. Результат анализирует ИИ.', 'Each question is timed and moves on automatically. AI analyses your result at the end.'],
  back: ['Artqa', 'Orqaga', 'Назад', 'Back'],
  result_great: ['🎉 Ájayıp nátiyje!', '🎉 Ajoyib natija!', '🎉 Отличный результат!', '🎉 Great job!'],
  result_ok: ['📚 Jaman emes — dawam etiń!', "📚 Yomon emas — davom eting!", '📚 Неплохо — продолжайте!', '📚 Not bad — keep learning!'],
  result_low: ['💪 Ósiw ushın orın bar!', "💪 O'sish uchun imkoniyat bor!", '💪 Есть куда расти!', '💪 Room to grow!'],
  correct: ['durıs', "to'g'ri", 'верно', 'correct'],
  final_passed: ['Juwmaqlawshı testten óttińiz (ótiw balı {n}%)', "Yakuniy testdan o'tdingiz (o'tish bali {n}%)", 'Итоговый тест сдан (проходной балл {n}%)', 'You passed the final test (pass mark {n}%)'],
  final_failed: ['Ótiw ushın keminde {n}% kerek — qayta urınıp kóriń', "O'tish uchun kamida {n}% kerak — qayta urinib ko'ring", 'Нужно минимум {n}% — попробуйте ещё раз', 'You need at least {n}% to pass — try again'],
  by_topic: ['Temalar boyınsha', "Mavzular bo'yicha", 'По темам', 'By topic'],
  review_answers: ['Juwaplardı kórip shıǵıw', "Javoblarni ko'rib chiqish", 'Разбор ответов', 'Review answers'],
  correct_answer: ['Durıs juwap', "To'g'ri javob", 'Правильный ответ', 'Correct answer'],
  cert_of_completion: ['Tamamlaw haqqında', 'Tugatganlik haqida', 'Об окончании курса', 'Certificate of completion'],
  cert_presented_to: ['Bul sertifikat beriledi', 'Ushbu sertifikat beriladi', 'Настоящий сертификат вручается', 'This certificate is presented to'],
  cert_for_completing: ['kurstı tabıslı tamamlaǵanı ushın:', 'kursni muvaffaqiyatli tugatgani uchun:', 'за успешное окончание курса', 'for successfully completing the course'],
  final_score: ['juwmaqlawshı ball', 'yakuniy ball', 'итоговый балл', 'final score'],
  date: ['Sáne', 'Sana', 'Дата', 'Date'],
  cert_id: ['Sertifikat ID', 'Sertifikat ID', 'ID сертификата', 'Certificate ID'],
  cert_verify: ['Tekseriw', 'Tekshirish', 'Проверка', 'Verify at'],
  print_pdf: ['Basıp shıǵarıw / PDF', 'Chop etish / PDF', 'Печать / PDF', 'Print / save PDF'],
  test: ['Test', 'Test', 'Тест', 'Test'],
  test_lesson: ['Sabaq testi', 'Dars testi', 'Тест урока', 'Lesson test'],
  test_level: ['Dárejelik test', 'Daraja testi', 'Тест уровня', 'Level test'],
  test_final: ['Juwmaqlawshı test', 'Yakuniy test', 'Итоговый тест', 'Final test'],

  // ── Profile ──
  my_profile: ['Meniń profilim', 'Mening profilim', 'Мой профиль', 'My profile'],
  profile_sub: ['Jeke maǵlıwmatlar, hújjetler, maqsetler hám keste', "Shaxsiy ma'lumotlar, hujjatlar, maqsadlar va jadval", 'Личные данные, документы, цели и расписание', 'Personal info, documents, goals and schedule'],
  ptab_info: ['Maǵlıwmatlar', "Ma'lumotlar", 'Данные', 'Info'],
  ptab_teaching: ['Oqıtıwshı profili', "O'qituvchi profili", 'Профиль преподавателя', 'Teacher profile'],
  ptab_documents: ['Hújjetler', 'Hujjatlar', 'Документы', 'Documents'],
  ptab_purpose: ['Maqset keńisligi', 'Maqsad maydoni', 'Пространство целей', 'Purpose Space'],
  ptab_schedule: ['Keste', 'Jadval', 'Расписание', 'Schedule'],
  ptab_activity: ['Nátiyjeler hám arzalar', 'Natijalar va arizalar', 'Результаты и отклики', 'Results & applications'],
  change_photo: ['Súwretti ózgertiw', "Rasmni o'zgartirish", 'Сменить фото', 'Change photo'],
  bio: ['Ózińiz haqqında', "O'zingiz haqingizda", 'О себе', 'About you'],
  bio_ph: ['Bilimińiz, tájiriybeńiz, kónlikpeleriniz...', "Ta'limingiz, tajribangiz, ko'nikmalaringiz...", 'Образование, опыт, навыки...', 'Your education, experience, skills...'],
  bio_hint: ['Ziyrek AI usı maǵlıwmattı karyera tallawında paydalanadı.', "Ziyrek AI bu ma'lumotni karyera tahlilida ishlatadi.", 'Ziyrek AI использует это для карьерного анализа.', 'Ziyrek AI uses this for your career analysis.'],
  account_type: ['Akkaunt túri', 'Akkaunt turi', 'Тип аккаунта', 'Account type'],
  open_to_work: ['Jumıs izlep atırman (shólkemler CV-ımdı kóre aladı)', "Ish qidiryapman (tashkilotlar CV'imni ko'ra oladi)", 'Ищу работу (организации видят моё резюме)', 'Open to work (organizations can see my CV)'],
  save_changes: ['Ózgerislerdi saqlaw', "O'zgarishlarni saqlash", 'Сохранить изменения', 'Save changes'],
  change_password: ['Paroldi ózgertiw', "Parolni o'zgartirish", 'Сменить пароль', 'Change password'],
  current_password: ['Házirgi parol', 'Joriy parol', 'Текущий пароль', 'Current password'],
  headline: ['Qısqasha tanıstırıw', 'Qisqacha tanishtiruv', 'Короткое описание', 'Headline'],
  headline_ph: ['Mısalı: Python oqıtıwshısı, 5 jıl tájiriybe', "Masalan: Python o'qituvchisi, 5 yil tajriba", 'Например: преподаватель Python, 5 лет опыта', 'e.g. Python teacher, 5 years of experience'],
  specialization: ['Qánigeligi', 'Mutaxassisligi', 'Специализация', 'Specialization'],
  experience_years: ['Tájiriybe (jıl)', 'Tajriba (yil)', 'Опыт (лет)', 'Experience (years)'],
  contact_email: ['Baylanıs email', 'Aloqa email', 'Email для связи', 'Contact email'],
  show_public_profile: ['Profilimdi oqıtıwshılar betinde kórsetiw', "Profilimni o'qituvchilar sahifasida ko'rsatish", 'Показывать профиль на странице преподавателей', 'Show my profile on the Teachers page'],
  view_public: ['Ashıq betti kóriw', "Ochiq sahifani ko'rish", 'Открыть публичную страницу', 'View public page'],
  certificates_uploaded: ['Sertifikatlarım', 'Sertifikatlarim', 'Мои сертификаты', 'My certificates'],
  awards: ['Sıylıqlar', 'Mukofotlar', 'Награды', 'Awards'],
  name: ['Atı', 'Nomi', 'Название', 'Name'],
  cv: ['Rezyume (CV)', 'Rezyume (CV)', 'Резюме (CV)', 'CV / Resume'],
  cv_uploaded: ['CV júklendi', 'CV yuklandi', 'Резюме загружено', 'CV uploaded'],
  view: ['Kóriw', "Ko'rish", 'Открыть', 'View'],
  cv_hint: ['PDF formatındaǵı CV-dı Ziyrek AI tolıq oqıp tallaydı.', "PDF formatdagi CV'ni Ziyrek AI to'liq o'qib tahlil qiladi.", 'Резюме в PDF Ziyrek AI прочитает и проанализирует полностью.', 'Ziyrek AI can read and analyse a PDF CV in full.'],
  replace_cv: ['CV-dı almastırıw', 'CV ni almashtirish', 'Заменить резюме', 'Replace CV'],
  upload_cv: ['CV júklew', 'CV yuklash', 'Загрузить резюме', 'Upload CV'],
  course_certificates: ['Platforma sertifikatları', 'Platforma sertifikatlari', 'Сертификаты платформы', 'Platform certificates'],
  edit_schedule: ['Kestedi ózgertiw', "Jadvalni o'zgartirish", 'Изменить занятие', 'Edit session'],
  add_schedule: ['Kestege qosıw', "Jadvalga qo'shish", 'Добавить занятие', 'Add to schedule'],
  schedule_title_ph: ['Mısalı: Python — 3-sabaq', 'Masalan: Python — 3-dars', 'Например: Python — урок 3', 'e.g. Python — lesson 3'],
  course: ['Kurs', 'Kurs', 'Курс', 'Course'],
  date_time: ['Sáne hám waqıt', 'Sana va vaqt', 'Дата и время', 'Date & time'],
  notes: ['Eskertpe', 'Izoh', 'Заметки', 'Notes'],
  cancel: ['Biykarlaw', 'Bekor qilish', 'Отмена', 'Cancel'],
  reminder_info: ['Sayt ashıq turǵanda sabaqtan 1 minut aldın eskertpe kórsetiledi.', "Sayt ochiq bo'lsa, darsdan 1 daqiqa oldin eslatma ko'rsatiladi.", 'Когда сайт открыт, напоминание появится за 1 минуту до занятия.', 'While the site is open you get a reminder 1 minute before each session.'],
  enable_notifications: ['Xabarlamalardı qosıw', 'Bildirishnomalarni yoqish', 'Включить уведомления', 'Enable notifications'],
  past_schedule: ['Ótken kesteler', "O'tgan jadval", 'Прошедшие занятия', 'Past sessions'],
  my_applications: ['Meniń arzalarım', 'Mening arizalarim', 'Мои отклики', 'My applications'],
  test_results: ['Test nátiyjeleri', 'Test natijalari', 'Результаты тестов', 'Test results'],
  take_test: ['Test tapsırıw', 'Test topshirish', 'Пройти тест', 'Take test'],
  profile_updated: ['Profil jańalandı', 'Profil yangilandi', 'Профиль обновлён', 'Profile updated'],
  wrong_password: ['Házirgi parol qáte.', "Joriy parol noto'g'ri.", 'Текущий пароль неверный.', 'Current password is wrong.'],
  purpose_title: ['Keleshektegi maqsetlerim', 'Kelajakdagi maqsadlarim', 'Мои цели на будущее', 'My future goals'],
  purpose_sub: ['Qızıǵıwshılıqlarıńız hám maqsetlerińizdi jazıń. AI sizge uqsas maqsetli adamlardı tabadı.', "Qiziqishlaringiz va maqsadlaringizni yozing. AI sizga o'xshash maqsadli odamlarni topadi.", 'Опишите интересы и цели. ИИ найдёт людей с похожими целями.', 'Describe your interests and goals. AI finds people with similar ones.'],
  purpose_ph: ['Mısalı: Men jasalma intellekt hám startaplarǵa qızıǵaman. Keleshekte óz IT kompaniyamdı ashqım keledi...', "Masalan: Men sun'iy intellekt va startaplarga qiziqaman. Kelajakda o'z IT kompaniyamni ochmoqchiman...", 'Например: интересуюсь ИИ и стартапами, хочу открыть свою IT-компанию...', 'e.g. I am interested in AI and startups and want to launch my own tech company...'],
  purpose_btn: ['Saqlaw hám uqsaslardı tabıw', "Saqlash va o'xshashlarni topish", 'Сохранить и найти похожих', 'Save & find similar people'],
  connection_requests: ['Baylanıs sorawları', "Bog'lanish so'rovlari", 'Запросы на контакт', 'Connection requests'],
  accept: ['Qabıllaw', 'Qabul qilish', 'Принять', 'Accept'],
  decline: ['Biykarlaw', 'Rad etish', 'Отклонить', 'Decline'],
  similar_people: ['Uqsas maqsetli adamlar', "O'xshash maqsadli odamlar", 'Люди с похожими целями', 'People with similar goals'],
  connected: ['Baylanıstı', "Bog'landi", 'На связи', 'Connected'],
  request_sent: ['Soraw jiberildi', "So'rov yuborildi", 'Запрос отправлен', 'Request sent'],
  connect: ['Baylanısıw', "Bog'lanish", 'Связаться', 'Connect'],
  no_matches: ['Házirshe uqsas adamlar tabılmadı.', "Hozircha o'xshash odamlar topilmadi.", 'Похожих людей пока не найдено.', 'No similar people found yet.'],
  my_connections: ['Meniń baylanıslarım', "Mening bog'lanishlarim", 'Мои контакты', 'My connections'],
  no_connections: ['Ele baylanıslar joq.', "Hali bog'lanishlar yo'q.", 'Контактов пока нет.', 'No connections yet.'],
  matches_found: ['{n} uqsas adam tabıldı', "{n} ta o'xshash odam topildi", 'Найдено похожих людей: {n}', '{n} similar people found'],
  wants_to_connect: ['siz benen baylanısqısı keledi', "siz bilan bog'lanmoqchi", 'хочет связаться с вами', 'wants to connect with you'],
  accepted_connection: ['baylanıs sorawıńızdı qabılladı', "bog'lanish so'rovingizni qabul qildi", 'принял(а) ваш запрос', 'accepted your connection request'],
  schedule_saved: ['Keste saqlandı', 'Jadval saqlandi', 'Занятие сохранено', 'Schedule saved'],
  no_notifications: ['Xabarlamalar joq.', "Bildirishnomalar yo'q.", 'Уведомлений нет.', 'No notifications.'],
  clear_all: ['Barlıǵın óshiriw', "Barchasini o'chirish", 'Очистить всё', 'Clear all'],

  // ── Ziyrek AI ──
  ai_title: ['Ziyrek AI — karyera keńesshisi', 'Ziyrek AI — karyera maslahatchisi', 'Ziyrek AI — карьерный консультант', 'Ziyrek AI — career advisor'],
  ai_sub: ['Rezyumeńizdi tallań hám jeke karyera keńeslerin alıń', 'Rezyumengizni tahlil qiling va shaxsiy karyera maslahatlarini oling', 'Проанализируйте резюме и получите персональные советы', 'Analyse your CV and get personal career advice'],
  ai_cv_analysis: ['Rezyume tallawı', 'Rezyume tahlili', 'Анализ резюме', 'CV analysis'],
  ai_readiness: ['Lawazımǵa tayarlıq', 'Lavozimga tayyorlik', 'Готовность к роли', 'Role readiness'],
  ai_skill_gaps: ['Jetispeytuǵın kónlikpeler', "Yetishmayotgan ko'nikmalar", 'Недостающие навыки', 'Skill gaps'],
  ai_matched_vacancies: ['Mas vakansiyalar', 'Mos vakansiyalar', 'Подходящие вакансии', 'Matching vacancies'],
  ai_recommended_courses: ['Usınılatuǵın kurslar', 'Tavsiya etilgan kurslar', 'Рекомендуемые курсы', 'Recommended courses'],
  ai_roadmap: ['Rawajlanıw jol kartası', "Rivojlanish yo'l xaritasi", 'Дорожная карта развития', 'Growth roadmap'],
  ai_no_items: ['Házirshe mas keletuǵın nárse joq.', "Hozircha mos keladigan narsa yo'q.", 'Пока ничего подходящего.', 'Nothing matching right now.'],
  ai_profile_incomplete: ['Profilińiz tolıq emes', "Profilingiz to'liq emas", 'Профиль заполнен не полностью', 'Your profile is incomplete'],
  ai_profile_hint: ['Jaqsıraq nátiyje ushın bio hám CV qosıń.', "Yaxshiroq natija uchun bio va CV qo'shing.", 'Добавьте биографию и резюме для лучшего результата.', 'Add a bio and CV for better results.'],
  complete_profile: ['Profildi toltırıw', "Profilni to'ldirish", 'Заполнить профиль', 'Complete profile'],
  ai_analyzing_long: ['Ziyrek AI tallap atır (30 sekundqa shekem)...', 'Ziyrek AI tahlil qilmoqda (30 soniyagacha)...', 'Ziyrek AI анализирует (до 30 секунд)...', 'Ziyrek AI is analysing (up to 30 seconds)...'],
  ai_reanalyze: ['Qayta tallaw', 'Qayta tahlil', 'Повторный анализ', 'Analyse again'],
  ai_analyze_btn: ['Tallawdı baslaw', 'Tahlilni boshlash', 'Начать анализ', 'Start analysis'],
  last_analysis: ['Sońǵı tallaw', "So'nggi tahlil", 'Последний анализ', 'Last analysis'],
  ai_empty: ['Tallawdı baslaw ushın joqarıdaǵı túymeni basıń.', 'Tahlilni boshlash uchun yuqoridagi tugmani bosing.', 'Нажмите кнопку выше, чтобы начать анализ.', 'Press the button above to start the analysis.'],
  ai_done: ['Tallaw tayar!', 'Tahlil tayyor!', 'Анализ готов!', 'Your analysis is ready!'],
  ai_error: ['AI tallawında qátelik. Keyinirek qaytalań.', 'AI tahlilida xatolik. Keyinroq qayta urinib ko‘ring.', 'Ошибка ИИ-анализа. Попробуйте позже.', 'AI analysis failed. Please try again later.'],
  ai_not_configured: ['AI ele qosılmaǵan: administrator serverde ANTHROPIC_API_KEY ornatıwı kerek.', "AI hali ulanmagan: administrator serverda ANTHROPIC_API_KEY o'rnatishi kerak.", 'ИИ ещё не подключён: администратору нужно указать ANTHROPIC_API_KEY на сервере.', 'AI is not connected yet: an administrator needs to set ANTHROPIC_API_KEY on the server.'],
  ai_not_configured_short: ['AI qosılmaǵan', 'AI ulanmagan', 'ИИ не подключён', 'AI not connected'],

  // ── Skill test ──
  skill_title: ['Kónlikpe testi', "Ko'nikma testi", 'Тест навыков', 'Skill test'],
  skill_sub: ['Hár túrli tarawlardan 20 soraw — kúshli hám ázzi táreplerińizdi biliń.', "Turli sohalardan 20 ta savol — kuchli va zaif tomonlaringizni biling.", '20 вопросов из разных областей — узнайте сильные и слабые стороны.', '20 questions across categories — find your strengths and gaps.'],
  no_questions_admin: ['Ele sorawlar joq. Admin sorawlar qosıwı kerek.', "Hali savollar yo'q. Admin savollar qo'shishi kerak.", 'Вопросов пока нет. Админ должен их добавить.', 'No questions yet. An admin needs to add some.'],
  last_result: ['Sońǵı nátiyje', "So'nggi natija", 'Последний результат', 'Last result'],
  strengths: ['Kúshli tárepler', 'Kuchli tomonlar', 'Сильные стороны', 'Strengths'],
  to_improve: ['Rawajlandırıw kerek', 'Rivojlantirish kerak', 'Что улучшить', 'To improve'],

  // ── Org & vacancy management ──
  new_application: ['jańa arza', 'yangi ariza', 'новый отклик', 'new application'],
  applied_ok: ['Arzańız jiberildi! Jaǵdayın profilde kóriń.', "Arizangiz yuborildi! Holatini profilda ko'ring.", 'Отклик отправлен! Статус — в профиле.', 'Application sent! Track its status in your profile.'],
  edit: ['Ózgertiw', "O'zgartirish", 'Изменить', 'Edit'],
  cancel_vacancy: ['Vakansiyanı biykarlaw', 'Vakansiyani bekor qilish', 'Отменить вакансию', 'Cancel vacancy'],
  reopen: ['Qayta ashıw', 'Qayta ochish', 'Открыть снова', 'Reopen'],
  cancel_warning: ['Vakansiya jabıladı. Sebep mindetli — ol barlıq arza bergenlerge jiberiledi hám AI tallaydı.', "Vakansiya yopiladi. Sabab majburiy — u barcha ariza berganlarga yuboriladi va AI tahlil qiladi.", 'Вакансия будет закрыта. Причина обязательна — её получат все откликнувшиеся, ИИ её проанализирует.', 'The vacancy will close. A reason is required — every applicant receives it, and AI analyses it.'],
  cancel_reason_ph: ['Mısalı: lawazım ishki kandidat penen toltırıldı, byudjet qısqardı...', "Masalan: lavozim ichki nomzod bilan to'ldirildi, byudjet qisqardi...", 'Например: позиция закрыта внутренним кандидатом, сокращён бюджет...', 'e.g. filled internally, budget cuts, project cancelled...'],
  confirm_cancel: ['Biykarlawdı tastıyıqlaw', 'Bekor qilishni tasdiqlash', 'Подтвердить отмену', 'Confirm cancellation'],
  edit_vacancy: ['Vakansiyanı ózgertiw', "Vakansiyani o'zgartirish", 'Редактировать вакансию', 'Edit vacancy'],
  vacancy_title: ['Lawazım atı', 'Lavozim nomi', 'Название должности', 'Job title'],
  vacancy_title_ph: ['Mısalı: Frontend dasturshı', 'Masalan: Frontend dasturchi', 'Например: Frontend-разработчик', 'e.g. Frontend developer'],
  organization: ['Shólkem', 'Tashkilot', 'Организация', 'Organization'],
  vacancy_desc_ph: ['Mindetler, talaplar, jumıs sharayatları...', 'Vazifalar, talablar, ish sharoitlari...', 'Обязанности, требования, условия...', 'Responsibilities, requirements, conditions...'],
  markdown_hint: ['Dizim ushın "- " hám qalıń jazıw ushın **tekst** paydalanıń.', 'Ro‘yxat uchun "- " va qalin yozuv uchun **matn** ishlating.', 'Используйте "- " для списков и **текст** для жирного.', 'Use "- " for lists and **text** for bold.'],
  reason_required: ['Sebebin jazıń.', 'Sababini yozing.', 'Укажите причину.', 'Please give a reason.'],
  vacancy_cancelled_ok: ['Vakansiya biykar etildi. {n} arza beriwshige xabar jiberildi.', "Vakansiya bekor qilindi. {n} nafar ariza beruvchiga xabar yuborildi.", 'Вакансия отменена. Уведомлено откликнувшихся: {n}.', 'Vacancy cancelled. {n} applicants were notified.'],
  deleted: ['Óshirildi', "O'chirildi", 'Удалено', 'Deleted'],
  no_cv: ['CV joq', "CV yo'q", 'Нет резюме', 'No CV'],
  update: ['Jańalaw', 'Yangilash', 'Обновить', 'Update'],
  candidates: ['Kandidatlar', 'Nomzodlar', 'Кандидаты', 'Candidates'],
  candidates_sub: ['Jumıs izlep atırǵan hám CV júklegen oqıwshılar', "Ish qidirayotgan va CV yuklagan o'quvchilar", 'Студенты, которые ищут работу и загрузили резюме', 'Students who are open to work and have uploaded a CV'],
  search_candidates: ['Kónlikpe yamasa at boyınsha izlew...', "Ko'nikma yoki ism bo'yicha qidirish...", 'Поиск по навыкам или имени...', 'Search by skill or name...'],
  candidates_note: ['Tek "Jumıs izlep atırman" dep belgilegen paydalanıwshılar kórsetiledi.', "Faqat \"Ish qidiryapman\" deb belgilagan foydalanuvchilar ko'rsatiladi.", 'Показаны только пользователи с отметкой «Ищу работу».', 'Only users who chose "Open to work" are shown.'],
  contact: ['Baylanıs', 'Aloqa', 'Связаться', 'Contact'],
  no_candidates: ['Házirshe kandidatlar joq.', "Hozircha nomzodlar yo'q.", 'Кандидатов пока нет.', 'No candidates yet.'],
  org_profile: ['Shólkem profili', 'Tashkilot profili', 'Профиль организации', 'Organization profile'],

  // ── Admin panel ──
  overview: ['Ulıwma kórinis', "Umumiy ko'rinish", 'Обзор', 'Overview'],
  submissions: ['Jiberilgen jumıslar', 'Yuborilgan ishlar', 'Сданные работы', 'Submissions'],
  skill_questions: ['Kónlikpe sorawları', "Ko'nikma savollari", 'Вопросы теста навыков', 'Skill questions'],
  skill_questions_sub: ['Ulıwma kónlikpe testi ushın sorawlar bankı', "Umumiy ko'nikma testi uchun savollar banki", 'Банк вопросов для общего теста навыков', 'Question bank for the general skill test'],
  users: ['Paydalanıwshılar', 'Foydalanuvchilar', 'Пользователи', 'Users'],
  latest_test_results: ['Sońǵı test nátiyjeleri', "So'nggi test natijalari", 'Последние результаты тестов', 'Latest test results'],
  published: ['Járiyalanǵan', 'Nashr etilgan', 'Опубликован', 'Published'],
  hidden: ['Jasırın', 'Yashirin', 'Скрыт', 'Hidden'],
  course_name: ['Kurs atı', 'Kurs nomi', 'Название курса', 'Course name'],
  description: ['Táriyp', 'Tavsif', 'Описание', 'Description'],
  category: ['Kategoriya', 'Kategoriya', 'Категория', 'Category'],
  category_ph: ['Mısalı: Programmalastırıw', 'Masalan: Dasturlash', 'Например: Программирование', 'e.g. Programming'],
  level: ['Dáreje', 'Daraja', 'Уровень', 'Level'],
  level_beginner: ['Baslawshı', "Boshlang'ich", 'Начальный', 'Beginner'],
  level_intermediate: ['Orta', "O'rta", 'Средний', 'Intermediate'],
  level_advanced: ['Joqarı', 'Yuqori', 'Продвинутый', 'Advanced'],
  thumbnail_url: ['Muqaba súwret URL', 'Muqova rasmi URL', 'URL обложки', 'Cover image URL'],
  or_upload_image: ['yamasa súwret júklew', 'yoki rasm yuklash', 'или загрузите изображение', 'or upload an image'],
  replace_image: ['Súwretti almastırıw', 'Rasmni almashtirish', 'Заменить изображение', 'Replace image'],
  publish_course: ['Kurstı járiyalaw (hámmege kórinedi)', "Kursni nashr etish (hammaga ko'rinadi)", 'Опубликовать курс (виден всем)', 'Publish course (visible to everyone)'],
  create: ['Jaratıw', 'Yaratish', 'Создать', 'Create'],
  course_created: ['Kurs jaratıldı! Endi sabaqlar qosıń.', "Kurs yaratildi! Endi darslar qo'shing.", 'Курс создан! Теперь добавьте уроки.', 'Course created! Now add lessons.'],
  video_type: ['Video túri', 'Video turi', 'Тип видео', 'Video type'],
  video_external: ['YouTube / Vimeo silteme', 'YouTube / Vimeo havola', 'Ссылка YouTube / Vimeo', 'YouTube / Vimeo link'],
  video_upload: ['Fayl júklew', 'Fayl yuklash', 'Загрузка файла', 'Uploaded file'],
  duration: ['Dawamlılıǵı', 'Davomiyligi', 'Длительность', 'Duration'],
  video_file: ['Video fayl', 'Video fayl', 'Видеофайл', 'Video file'],
  replace_video: ['Videonı almastırıw', 'Videoni almashtirish', 'Заменить видео', 'Replace video'],
  choose_video: ['Video tańlaw', 'Video tanlash', 'Выбрать видео', 'Choose video'],
  video_hint: ['Úlken videolar ushın YouTube silteme usınıladı (serverdi jeńillestiredi).', 'Katta videolar uchun YouTube havola tavsiya etiladi (serverni yengillashtiradi).', 'Для больших видео лучше ссылка YouTube (меньше нагрузка на сервер).', 'For large videos a YouTube link is recommended (lighter on the server).'],
  order: ['Tártip', 'Tartib', 'Порядок', 'Order'],
  course_details: ['Kurs maǵlıwmatları', "Kurs ma'lumotlari", 'Данные курса', 'Course details'],
  confirm_delete_course: ['Kurs, onıń sabaqları, testleri hám nátiyjeleri tolıq óshiriledi. Dawam etemiz be?', "Kurs, uning darslari, testlari va natijalari to'liq o'chiriladi. Davom etamizmi?", 'Курс, его уроки, тесты и результаты будут удалены. Продолжить?', 'The course and all its lessons, tests and results will be deleted. Continue?'],
  delete_course: ['Kurstı óshiriw', "Kursni o'chirish", 'Удалить курс', 'Delete course'],
  add_lesson: ['Sabaq qosıw', "Dars qo'shish", 'Добавить урок', 'Add lesson'],
  tests: ['Testler', 'Testlar', 'Тесты', 'Tests'],
  no_questions_short: ['sorawlar joq', "savollar yo'q", 'нет вопросов', 'no questions'],
  no_tests: ['Ele testler joq.', "Hali testlar yo'q.", 'Тестов пока нет.', 'No tests yet.'],
  test_title: ['Test atı', 'Test nomi', 'Название теста', 'Test title'],
  test_type: ['Test túri', 'Test turi', 'Тип теста', 'Test type'],
  for_lesson_tests: ['sabaq testi ushın', 'dars testi uchun', 'для теста урока', 'for lesson tests'],
  time_limit: ['Waqıt (minut)', 'Vaqt (daqiqa)', 'Время (мин)', 'Time limit (min)'],
  add_test: ['Test qosıw', "Test qo'shish", 'Добавить тест', 'Add test'],
  add_assignment: ['Tapsırma qosıw', "Topshiriq qo'shish", 'Добавить задание', 'Add assignment'],
  no_students: ['Ele oqıwshılar joq.', "Hali o'quvchilar yo'q.", 'Студентов пока нет.', 'No students yet.'],
  preview: ['Aldın kóriw', "Oldindan ko'rish", 'Предпросмотр', 'Preview'],
  open_classroom: ['Klassqa kiriw', 'Sinfga kirish', 'Открыть класс', 'Open classroom'],
  lesson_added: ['Sabaq qosıldı', "Dars qo'shildi", 'Урок добавлен', 'Lesson added'],
  lesson_required: ['Sabaq testi ushın sabaqtı tańlań.', 'Dars testi uchun darsni tanlang.', 'Для теста урока выберите урок.', 'Choose a lesson for a lesson test.'],
  test_created: ['Test jaratıldı. Endi sorawlar qosıń.', "Test yaratildi. Endi savollar qo'shing.", 'Тест создан. Теперь добавьте вопросы.', 'Test created. Now add questions.'],
  question: ['Soraw', 'Savol', 'Вопрос', 'Question'],
  option: ['Variant', 'Variant', 'Вариант', 'Option'],
  topic: ['Tema', 'Mavzu', 'Тема', 'Topic'],
  add_question: ['Soraw qosıw', "Savol qo'shish", 'Добавить вопрос', 'Add question'],
  bulk_hint: ['Hár bir soraw bos qatar menen ajıratıladı. Variantlar "a)", "b)"... menen, durıs juwap "answer: b" túrinde.', "Har bir savol bo'sh qator bilan ajratiladi. Variantlar \"a)\", \"b)\"... bilan, to'g'ri javob \"answer: b\" ko'rinishida.", 'Вопросы разделяются пустой строкой. Варианты — «a)», «b)»…, правильный ответ — «answer: b».', 'Separate questions with an empty line. Options start with "a)", "b)"…; the correct one is "answer: b".'],
  import: ['Import', 'Import', 'Импорт', 'Import'],
  ai_gen_topic: ['Tema yamasa tekst', 'Mavzu yoki matn', 'Тема или текст', 'Topic or text'],
  ai_gen_topic_ph: ['Mısalı: Python dizimleri hám cikller', "Masalan: Python ro'yxatlari va sikllar", 'Например: списки и циклы в Python', 'e.g. Python lists and loops'],
  difficulty: ['Qıyınlıq', 'Qiyinlik', 'Сложность', 'Difficulty'],
  diff_easy: ['Ańsat', 'Oson', 'Лёгкий', 'Easy'],
  diff_medium: ['Orta', "O'rta", 'Средний', 'Medium'],
  diff_hard: ['Qıyın', 'Qiyin', 'Сложный', 'Hard'],
  count: ['Sanı', 'Soni', 'Количество', 'Count'],
  ai_generating: ['AI sorawlar jazıp atır...', 'AI savollar yozmoqda...', 'ИИ пишет вопросы...', 'AI is writing questions...'],
  ai_generate: ['AI menen jaratıw', 'AI bilan yaratish', 'Создать с ИИ', 'Generate with AI'],
  ai_generate_questions: ['AI menen sorawlar jaratıw', 'AI bilan savollar yaratish', 'Создать вопросы с ИИ', 'Generate questions with AI'],
  bulk_import: ['Kóp sorawdı import etiw', "Ko'p savolni import qilish", 'Массовый импорт', 'Bulk import'],
  delete_test: ['Testti óshiriw', "Testni o'chirish", 'Удалить тест', 'Delete test'],
  imported: ['{n} soraw qosıldı', "{n} ta savol qo'shildi", 'Добавлено вопросов: {n}', '{n} questions added'],
  sub_submitted: ['Tekseriwdi kútpekte', 'Tekshiruvni kutmoqda', 'Ожидает проверки', 'Awaiting review'],
  sub_reviewed: ['Bahalandı', 'Baholandi', 'Оценено', 'Reviewed'],
  teacher_comment: ['Oqıtıwshı pikiri', "O'qituvchi izohi", 'Комментарий преподавателя', 'Teacher comment'],
  save_review: ['Bahanı saqlaw', 'Bahoni saqlash', 'Сохранить оценку', 'Save review'],
  issue_certificate: ['Sertifikat beriw', 'Sertifikat berish', 'Выдать сертификат', 'Issue a certificate'],
  student_email: ['Oqıwshı emaili', "O'quvchi emaili", 'Email студента', 'Student email'],
  score: ['Ball', 'Ball', 'Балл', 'Score'],
  optional_file: ['Fayl (májbúriy emes)', 'Fayl (ixtiyoriy)', 'Файл (необязательно)', 'File (optional)'],
  issue: ['Beriw', 'Berish', 'Выдать', 'Issue'],
  auto_cert_note: ['Kurs tolıq tamamlanǵanda sertifikat avtomat beriledi.', "Kurs to'liq tugatilganda sertifikat avtomatik beriladi.", 'При полном прохождении курса сертификат выдаётся автоматически.', 'Certificates are also issued automatically on course completion.'],
  issued_certificates: ['Berilgen sertifikatlar', 'Berilgan sertifikatlar', 'Выданные сертификаты', 'Issued certificates'],
  user_not_found: ['Bul email menen paydalanıwshı tabılmadı.', 'Bu email bilan foydalanuvchi topilmadi.', 'Пользователь с таким email не найден.', 'No user with this email.'],
  search_users: ['At yamasa email boyınsha izlew...', "Ism yoki email bo'yicha qidirish...", 'Поиск по имени или email...', 'Search by name or email...'],
  pending_approval: ['Tastıyıqlawdı kútpekte', 'Tasdiqlashni kutmoqda', 'Ожидают подтверждения', 'Pending approval'],
  pending: ['kútpekte', 'kutmoqda', 'ожидает', 'pending'],
  user: ['Paydalanıwshı', 'Foydalanuvchi', 'Пользователь', 'User'],
  role: ['Roli', 'Roli', 'Роль', 'Role'],
  joined: ['Qosıldı', "Qo'shildi", 'Регистрация', 'Joined'],
  role_user: ['Paydalanıwshı', 'Foydalanuvchi', 'Пользователь', 'User'],
  role_teacher: ['Oqıtıwshı', "O'qituvchi", 'Преподаватель', 'Teacher'],
  role_admin: ['Admin', 'Admin', 'Админ', 'Admin'],
  approve: ['Tastıyıqlaw', 'Tasdiqlash', 'Подтвердить', 'Approve'],
  confirm_delete_user: ['Paydalanıwshı hám onıń barlıq maǵlıwmatları óshiriledi. Dawam etemiz be?', "Foydalanuvchi va uning barcha ma'lumotlari o'chiriladi. Davom etamizmi?", 'Пользователь и все его данные будут удалены. Продолжить?', 'The user and all their data will be deleted. Continue?'],
  nothing_found: ['Hesh nárse tabılmadı.', 'Hech narsa topilmadi.', 'Ничего не найдено.', 'Nothing found.'],
  teacher_approved_title: ['Oqıtıwshı akkauntıńız tastıyıqlandı', "O'qituvchi akkauntingiz tasdiqlandi", 'Аккаунт преподавателя подтверждён', 'Your teacher account is approved'],
  teacher_approved_body: ['Endi kurslar jarata alasız.', 'Endi kurslar yarata olasiz.', 'Теперь вы можете создавать курсы.', 'You can now create courses.'],
  community_admin_sub: ['"Járdem hám jámiyet" betiniń mazmunı', '"Yordam va hamjamiyat" sahifasi mazmuni', 'Содержимое страницы «Помощь и сообщество»', 'Content of the Help & community page'],
  ctype_video_explanation: ['Video túsindirmeler', 'Video tushuntirishlar', 'Видео-объяснения', 'Video guides'],
  ctype_useful_link: ['Paydalı siltemeler', 'Foydali havolalar', 'Полезные ссылки', 'Useful links'],
  ctype_investor: ['Investorlar', 'Investorlar', 'Инвесторы', 'Investors'],
  ctype_event: ['Ilajlar', 'Tadbirlar', 'События', 'Events'],
  ctype_news: ['Jańalıqlar', 'Yangiliklar', 'Новости', 'News'],
  ctype_support_info: ['Qollap-quwatlaw', "Qo'llab-quvvatlash", 'Поддержка', 'Support'],
  ctype_director: ['Tiykarlawshılar', 'Asoschilar', 'Основатели', 'Founders'],
  video_url: ['Video silteme (YouTube)', 'Video havola (YouTube)', 'Ссылка на видео (YouTube)', 'Video link (YouTube)'],
  telegram_url: ['Telegram bot silteme', 'Telegram bot havolasi', 'Ссылка на Telegram-бот', 'Telegram bot link'],
  link: ['Silteme', 'Havola', 'Ссылка', 'Link'],
  platform: ['Platforma', 'Platforma', 'Платформа', 'Platform'],
  photo: ['Súwret', 'Rasm', 'Фото', 'Photo'],
  or_upload_video: ['yamasa video júklew', 'yoki video yuklash', 'или загрузите видео', 'or upload a video'],
  visible: ['Kórinedi', "Ko'rinadi", 'Виден', 'Visible'],
  saving: ['Saqlanbaqta...', 'Saqlanmoqda...', 'Сохранение...', 'Saving...'],
  external: ['Sırtqı', 'Tashqi', 'Внешний', 'External'],
  support_info: ['Qollap-quwatlaw', "Qo'llab-quvvatlash", 'Поддержка', 'Support'],

  // ── Privacy ──
  privacy_text: [
    '## Qanday maǵlıwmatlar jıynaladı\n- At, email, telefon, ID nomeri (kursqa jazılıw ushın), profil maǵlıwmatları hám júklengen hújjetler.\n- Test nátiyjeleri, tapsırmalar hám oqıw progressi.\n\n## Ne ushın\n- Platformanı islew, sertifikat beriw hám jumıs berwshilerge (tek siz ruxsat bergende) CV kórsetiw ushın.\n- AI tallawı ushın maǵlıwmatlar Anthropic Claude API arqalı qayta islenedi.\n\n## Sizdiń huqıqlarıńız\n- Profilde maǵlıwmatlarıńızdı ózgerte hám hújjetlerdi óshire alasız. Akkauntıńızdı tolıq óshiriw ushın qollap-quwatlaw xızmetine jazıń.',
    "## Qanday ma'lumotlar yig'iladi\n- Ism, email, telefon, ID raqami (kursga yozilish uchun), profil ma'lumotlari va yuklangan hujjatlar.\n- Test natijalari, topshiriqlar va o'qish progressi.\n\n## Nima uchun\n- Platforma ishlashi, sertifikat berish va ish beruvchilarga (faqat siz ruxsat bersangiz) CV ko'rsatish uchun.\n- AI tahlili uchun ma'lumotlar Anthropic Claude API orqali qayta ishlanadi.\n\n## Sizning huquqlaringiz\n- Profilda ma'lumotlaringizni o'zgartirishingiz va hujjatlarni o'chirishingiz mumkin. Akkauntni to'liq o'chirish uchun qo'llab-quvvatlash xizmatiga yozing.",
    '## Какие данные мы собираем\n- Имя, email, телефон, номер ID (для записи на курс), данные профиля и загруженные документы.\n- Результаты тестов, задания и прогресс обучения.\n\n## Зачем\n- Для работы платформы, выдачи сертификатов и показа резюме работодателям (только с вашего согласия).\n- Для ИИ-анализа данные обрабатываются через Anthropic Claude API.\n\n## Ваши права\n- Вы можете изменить данные и удалить документы в профиле. Для полного удаления аккаунта напишите в поддержку.',
    '## What we collect\n- Name, email, phone, ID number (for course enrollment), profile details and uploaded documents.\n- Test results, assignments and learning progress.\n\n## Why\n- To run the platform, issue certificates and show your CV to employers (only if you opt in).\n- For AI analysis, data is processed through the Anthropic Claude API.\n\n## Your rights\n- You can edit your data and delete documents in your profile. To delete your account completely, contact support.',
  ],
};
